development:
  adapter: mysql2
  database: audio_hawk_dev
  username: root
  password:
  host: localhost
test:
  adapter: mysql2
  database: audio_hawk_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql2
  database: audio_hawk_prod
  username: root
  password:
  host: localhost
